import type { Metadata } from "next";
import { montserrat } from "./style/fonts/fonts"; 
import "./globals.scss";

export const metadata: Metadata = {
  title: {
    template: "%s | Smart Home", // %s will be replaced by the current page title (%s looks for a string)
    default: "Smart Home",
  },
  description: "Generated by E-Thon for Mobicom as a tryout project",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body>{children}</body>
    </html>
  );
}
